/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    media_partners: MediaPartner;
    products: Product;
    hero_slider: HeroSlider;
    partner: Partner;
    partner_category: PartnerCategory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    media_partners: MediaPartnersSelect<false> | MediaPartnersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    hero_slider: HeroSliderSelect<false> | HeroSliderSelect<true>;
    partner: PartnerSelect<false> | PartnerSelect<true>;
    partner_category: PartnerCategorySelect<false> | PartnerCategorySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    technical_work: TechnicalWork;
    meet: Meet;
  };
  globalsSelect: {
    technical_work: TechnicalWorkSelect<false> | TechnicalWorkSelect<true>;
    meet: MeetSelect<false> | MeetSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_partners".
 */
export interface MediaPartner {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  mark?: ('none' | 'popular' | 'new' | 'sale') | null;
  type: 'stickers' | 'flavours' | 'merch' | 'frames';
  /**
   * Если выключено — товар не будет возвращаться в API для публичного доступа
   */
  active: boolean;
  inStock: boolean;
  name: string;
  /**
   * Оставь пустым — сгенерируется из названия
   */
  slug?: string | null;
  mainImage: number | Media;
  /**
   * Дополнительные фото товара (можно несколько)
   */
  gallery?: (number | Media)[] | null;
  pricing: {
    price: number;
    /**
     * Можно оставить пустым
     */
    oldPrice?: number | null;
  };
  characteristics?:
    | {
        category: string;
        values: {
          label: string;
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Длинный SEO-текст (контент на странице товара)
   */
  seoText?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_slider".
 */
export interface HeroSlider {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  detail_link: {
    title: string;
    url: string;
  };
  /**
   * Если выключено — товар не будет возвращаться в API для публичного доступа
   */
  active: boolean;
  bg_image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner".
 */
export interface Partner {
  id: number;
  /**
   * Оставь пустым — сгенерируется из названия
   */
  slug: string;
  /**
   * Если выключено — компания не будет возвращаться в API для публичного доступа
   */
  active: boolean;
  /**
   * Если включено — компания будет в ЧС
   */
  blacklist: boolean;
  /**
   * Если проверенная — отметить
   */
  verified: boolean;
  logo?: (number | null) | MediaPartner;
  /**
   * Фото процесса работ компании (желательно несколько)
   */
  gallery?: (number | MediaPartner)[] | null;
  title: string;
  /**
   * Описание партнера (что продает/производит)
   */
  description: string;
  address?: string | null;
  /**
   * Выбрать категории принадлежащие компании
   */
  categories: (number | PartnerCategory)[];
  /**
   * Размер скидки для клубных пользователей
   */
  discount?:
    | (
        | '5'
        | '10'
        | '15'
        | '20'
        | '25'
        | '30'
        | '35'
        | '40'
        | '45'
        | '50'
        | '55'
        | '60'
        | '65'
        | '70'
        | '75'
        | '80'
        | '85'
        | '90'
        | '95'
        | '100'
      )
    | null;
  contacts?: {
    /**
     * Ссылка на Instagram
     */
    instagram?: string | null;
    /**
     * Ссылка на Telegram
     */
    telegram?: string | null;
    /**
     * Ссылка на MAX
     */
    max?: string | null;
    /**
     * Ссылка на VK
     */
    vk?: string | null;
    /**
     * Ссылка на профиль Avito
     */
    avito?: string | null;
    phones?:
      | {
          phone: string;
          id?: string | null;
        }[]
      | null;
    emails?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Ссылка на сайт компании
     */
    site?: string | null;
    /**
     * Ссылка на профиль организации в Яндекс Картах
     */
    yandexMaps?: string | null;
  };
  /**
   * Сортировка компаний
   */
  sort: number;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner_category".
 */
export interface PartnerCategory {
  id: number;
  /**
   * Название категории на русском
   */
  title: string;
  /**
   * Автоматически генерируется из названия
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media_partners';
        value: number | MediaPartner;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'hero_slider';
        value: number | HeroSlider;
      } | null)
    | ({
        relationTo: 'partner';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'partner_category';
        value: number | PartnerCategory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_partners_select".
 */
export interface MediaPartnersSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  mark?: T;
  type?: T;
  active?: T;
  inStock?: T;
  name?: T;
  slug?: T;
  mainImage?: T;
  gallery?: T;
  pricing?:
    | T
    | {
        price?: T;
        oldPrice?: T;
      };
  characteristics?:
    | T
    | {
        category?: T;
        values?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  description?: T;
  seoText?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_slider_select".
 */
export interface HeroSliderSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  detail_link?:
    | T
    | {
        title?: T;
        url?: T;
      };
  active?: T;
  bg_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner_select".
 */
export interface PartnerSelect<T extends boolean = true> {
  slug?: T;
  active?: T;
  blacklist?: T;
  verified?: T;
  logo?: T;
  gallery?: T;
  title?: T;
  description?: T;
  address?: T;
  categories?: T;
  discount?: T;
  contacts?:
    | T
    | {
        instagram?: T;
        telegram?: T;
        max?: T;
        vk?: T;
        avito?: T;
        phones?:
          | T
          | {
              phone?: T;
              id?: T;
            };
        emails?:
          | T
          | {
              email?: T;
              id?: T;
            };
        site?: T;
        yandexMaps?: T;
      };
  sort?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner_category_select".
 */
export interface PartnerCategorySelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technical_work".
 */
export interface TechnicalWork {
  id: number;
  /**
   * Если выключено — сайт будет недоступен для пользования
   */
  active: boolean;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meet".
 */
export interface Meet {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coordinates: {
    lat: number;
    lng: number;
  };
  address: string;
  address_link?: string | null;
  date: string;
  date_tz: SupportedTimezones;
  /**
   * Если выключено — событие не будет возвращаться в API для публичного доступа
   */
  active: boolean;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technical_work_select".
 */
export interface TechnicalWorkSelect<T extends boolean = true> {
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meet_select".
 */
export interface MeetSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  address?: T;
  address_link?: T;
  date?: T;
  date_tz?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}